ccprojects/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import ProjectView,AddDetails,ChangeProjectStatus,ImpactView,Hierarchy_Data,ImpactConfirmed
# APP --> PROJECTS

#app_name="ccprojects" 

urlpatterns = [
    # Old Patterns
    # ------------
    url(r'^viewproject/$',ProjectView.as_view(),name='viewproject'),
    url(r'^(?P<project_id>[0-9]+)/viewimpacts/$',ImpactView.as_view(),name='viewimpacts'),
    # New Patterns
    # ------------
    # Add new impact on existing project
    url(r'^addnew/(?P<change_target>[a-zA-Z]+)/(?P<project_id>[0-9]+)/$',AddDetails.as_view(),name='addnewimpact'),
    # Modify existing impact
    url(r'^modify/(?P<change_target>[a-zA-Z]+)/(?P<project_id>[0-9]+)/(?P<change_id>[0-9]+)/$',AddDetails.as_view(),name='modifyimpact'),
    url(r'^modify/(?P<group_target>[a-zA-Z]+)/(?P<change_target>[a-zA-Z]+)/(?P<project_id>[0-9]+)/(?P<change_id>[0-9]+)/$',AddDetails.as_view(),name='altimpact'),
    # Modify existing project status_flag set to existing to distinguish between addnewproject
    url(r'^modify/(?P<change_target>[a-zA-Z]+)/(?P<status_flag>[a-zA-Z]+)/(?P<project_id>[0-9]+)/$',AddDetails.as_view(),name='modifyproject'),
    # Add new project
    url(r'^addnew/(?P<change_target>[a-zA-Z]+)/$',AddDetails.as_view(),name='addnewproject'),
    # Change Project Status
    url(r'^project_status/(?P<project_id>[0-9]+)/$',ChangeProjectStatus.as_view(),name='chgpstatus'),
    url(r'^confirmation/(?P<project_id>[0-9]+)/(?P<change_id>[0-9]+)/$',ImpactConfirmed.as_view(),name='chgconfirmed'),
    
    # Impact post and return
    url(r'^hierarchy_data/$',Hierarchy_Data.as_view(),name='hdata'),


]

ccprojects/forms.py
"""
------------------------------------------------------------------------
Title: APP - Project - Add Project - View - mod 2
Author: Matthew May
Date: 2016-03-01
Notes: Move to using form views
Notes: 2017-02-06 This will be using a dynamic class to build the 
Notes: Form which will then be called back in the view
------------------------------------------------------------------------
"""
from django import forms  
from .models import ProjectStructure,UserProjects,ProjectStatus#,UploadFile
from ccchange.models import ProjectChange

class AddProjectForm(forms.Form):  
    
    # Form options add project
    # ------------------------
    projectname = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder':'Project Name','class':'form-control'}))
    projectdesc = forms.CharField(required=True,widget=forms.Textarea(attrs={'placeholder':'Detailed description of the project','rows':'4','class':'form-control'}))
    benefitdesc = forms.CharField(required=True,widget=forms.Textarea(attrs={'placeholder':'Detailed description of the project','rows':'4','class':'form-control'}))
    customerimpact = forms.CharField(required=True,widget=forms.Textarea(attrs={'placeholder':'Description of impact to customer','rows':'3','class':'form-control'}))
    driver = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder':'Who is driving the project','class':'form-control'}))
 

 
class EditProjectForm(forms.Form): 
 
    changenote = forms.CharField(required=True,widget=forms.Textarea(attrs={'placeholder':'Add a note...','rows':'6','class':'form-control'}))
    datestart = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control pickadate','id':'datestart','value':'None','placeholder':'Start Date'}))
    dateend = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control pickadate','id':'dateend','value':'None','placeholder':'End Date'}))
 


#class AddNoteModal(forms.Form):
#    changenote = forms.CharField(required=True,widget=forms.Textarea(attrs={'placeholder':'Add a note...','rows':'6','class':'form-control'}))

#class CloseProjectModal(forms.Form):
#    pass

#class AddAttachment(forms.Form):
#    pid = forms.CharField(required=True,widget=forms.TextInput(attrs={'type':'hidden'}))

ccprojects/templates/ccprojects/Backup-2017-01-31/ccaddproject.html
{% extends "base.html" %}


{% block title %}AddProject{% endblock %}






					{% block main_content%}

<!-- 2 columns form -->
					<form method="POST">
					{% csrf_token %}
						<div class="panel panel-flat">
							<div class="panel-heading">
								<h5 class="panel-title">Add Project</h5>
								<div class="heading-elements">
									<ul class="icons-list">
				                		<li><a data-action="collapse"></a></li>
				                		<li><a data-action="reload"></a></li>
				                		<li><a data-action="close"></a></li>
				                	</ul>
			                	</div>
							</div>

							<div class="panel-body">
								<div class="row">
									<div class="col-md-6">
										<fieldset>
											<legend class="text-semibold"><i class="icon-reading position-left"></i>Project Details</legend>

											<div class="form-group">
												<label>Project Name:</label>
												{{ form.projectname }}
											</div>

											<div class="form-group">
												<label>Description:</label>
												{{ form.projectdesc }}
											</div>

											<div class="form-group">
												<label>Project Benefit:</label>
												{{ form.benefitdesc }}
											</div>

											<div class="form-group">
												<label>Customer Impact:</label>
												{{ form.customerimpact }}
											</div>

											<div class="form-group">
												<label>Driver:</label>
												{{ form.driver }}
											</div>

										</fieldset>
									</div>

									<div class="col-md-6">
										<fieldset>
						                	<legend class="text-semibold"><i class="icon-truck position-left"></i>Project Information</legend>

											<div class="row">
												<div class="col-md-6">
													<div class="form-group">
														<label>Benefit:</label>
														{{ form.benefitoptions }}
													</div>
												</div>

												<div class="col-md-6">
													<div class="form-group">
														<label>Project Health:</label>
														{{ form.healthoptions }}
													</div>
												</div>
											</div>


											<div class="row">
												<div class="col-md-6">
													<div class="form-group">
														<label>Change Size:</label>
														{{ form.changeoptions }}
													</div>
												</div>

												<div class="col-md-6">
													<div class="form-group">
														<label>Customer Volume:</label>
														{{ form.voloptions }}
													</div>
												</div>
											</div>


											<div class="row">

												<div class="col-md-6">
													<div class="form-group">
														<label>Customer Care:</label>
														{{ form.careoptions }}
													</div>
												</div>
									

											
												<div class="col-md-6">
													<div class="form-group">
														<label>Change Type:</label>
														{{ form.changetypeoptions }}
													</div>
												</div>
											</div>


											<div class="row">

												<div class="col-md-6">
													<div class="form-group">
														<label>Project Status:</label>
														{{ form.statusoptions }}
													</div>
												</div>


												<div class="col-md-6">
													<div class="form-group">
														<label>Group Category:</label>
														{{ form.categoryoptions }}
													</div>
												</div>


												<div class="row">
												<div class="col-md-6">
													<div class="form-group">
														<label>Confirmed:</label>
														{{ form.confirmedoptions }}
													</div>
												</div>

									

											

												<div class="col-md-6">
													<div class="form-group">
														<label>Impact Level:</label>
														{{ form.ileveloptions }}
													</div>
												</div>


                                       			</div>

                                       			<div class="row">

												<div class="col-md-6">
													<div class="form-group">
														<label>Impact Type:</label>
														{{ form.itypeoptions }}
													</div>
												</div>
												

										

												<div class="col-md-6">
													<div class="form-group">
														<label>Project Level:</label>
														{{ form.leveloptions }}
													</div>
												</div>


                                            </div> 

										</fieldset>
									</div>
								</div>

								<div class="text-right row">
								    <button type="submit" class="btn btn-danger" name="cancelbtn">Cancel</button>
									<button type="submit" class="btn btn-primary" name="addprojectbtn">Submit form <i class="icon-arrow-right14 position-right"></i></button>
								</div>
							</div>
						</div>
					</form>
					<!-- /2 columns form -->		       




					{% endblock %}

ccprojects/templates/ccprojects/Backup-2017-01-31/ccviewprojects.html
{% extends "base.html" %}


{% block title %}Project View{% endblock %}



-->



					{% block main_content%}

		               <div class="panel panel-white">
								<div class="panel-heading">
									<h6 class="panel-title">View Projects</h6>
									<div class="heading-elements">
										<ul class="icons-list">
					                		<li><a data-action="collapse" data-popup="tooltip" title="Collapse"></a></li>
					                		<li><a data-action="reload" data-popup="tooltip" title="Reload"></a></li>
					                		<li><a data-action="close" data-popup="tooltip" title="Close"></a></li>
					                	</ul>
				                	</div>
								</div>

						<table class="table datatable-responsive table-bordered table-striped table-hover bg-info-800">
							<thead>
										<tr>
											<th>Id</th>
											<th>Project Name</th>
											<th>Description</th>
											<th>Project Benefit</th>
											<th>Status</th>
											<th>Date Created</th>
											<th>Action</th>
										</tr>
							</thead>
							<tbody>
								   {% for project in projectdata %}
      
                                    <tr>
                                        
                                      <td>{{ project.id }}</td>
                                      <td>{{ project.project_name }}</td>
                                      <td>{{ project.description }}</td>
                                      <td>{{ project.benefit_desc }}</td>
                                      <td>Not yet implemented</td>
                                      <td>{{ project.created_on }}</td>

									  <td class="text-center">
										<ul class="icons-list">
											<li class="dropdown">
												<a href="#" class="dropdown-toggle" data-toggle="dropdown">
													<i class="icon-menu9"></i>
												</a>
												<ul class="dropdown-menu dropdown-menu-right">
													<!--<li><a href="#"><i class="icon-eye"></i> Review</a></li>-->
		<li><a href="/projects/update/{{ project.id }}/"><i class="icon-pencil"></i> Edit</a></li>
		<li><a data-toggle="modal" data-target="#modal_add_note" data-pname="{{ project.project_name }}" data-pid="{{ project.id }}" data-pdesc="{{ project.description }}" 
		       data-pdate="{{ project.created_on }}"><i class="icon-clipboard3"></i> Add Note</a></li>
		<li><a data-toggle="modal" data-target="#modal_add_attachments" data-pname="{{ project.project_name }}" data-pid="{{ project.id }}" data-pdesc="{{ project.description }}" 
		       data-pdate="{{ project.created_on }}"><i class="icon-file-plus"></i> Attachments</a></li>
		<li><a data-toggle="modal" data-target="#modal_close_form" data-pname="{{ project.project_name }}" data-pid="{{ project.id }}" data-pdesc="{{ project.description }}" 
		       data-pdate="{{ project.created_on }}"><i class="icon-close2"></i> Close</a> </li>
												</ul>
											</li>
										</ul>
									  </td>

                                      
                                    </tr>
                                  
                                    {% endfor %}
							</tbody>
						</table>
					</div>
					<!-- /basic responsive configuration -->

<!--
This is for any and all modals
Close project modal dialog note this needs more work. An ajax script is required to produce the response and send it to the correct Django class
There is some documentation/instructions on how to do this in the documents folder of the ccompass repo
-->
                    <!-- Add Note Modal -->
					<div id="modal_add_note" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header bg-danger">
									<button type="button" class="close" data-dismiss="modal">&times;</button>
									<h5 class="modal-title">Project Notes</h5>
								</div>

								<form action="#">
									<div class="modal-body">

									<h6 class="text-semibold">Notes...</h6>
									<p>Add a note or comment about this project</p>

									<hr>
										<div class="form-group">	
										<textarea class="form-control" cols="40" id="id_changenote" name="changenote" placeholder="Note..." rows="6"></textarea>
										</div>
									</div>


									<div class="modal-footer">
										<button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
										<!-- Below is not yet implemented -->
										<button type="submit" class="btn btn-primary" data-dismiss="modal">Add Attachment</button>
									</div>
								</form>
							</div>
						</div>
					</div>
					<!-- /vertical form modal -->


   <!-- Add Attachments Modal -->
					<div id="modal_add_attachments" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header bg-danger">
									<button type="button" class="close" data-dismiss="modal">&times;</button>
									<h5 class="modal-title">Add Attachment</h5>
								</div>

								<form action="#">



					  <div class="panel panel-flat">
						<div class="panel-heading">
							<div class="heading-elements">
								<ul class="icons-list">
			                		<li><a data-action="collapse"></a></li>
			                		<li><a data-action="reload"></a></li>
			                		<li><a data-action="close"></a></li>
			                	</ul>
		                	</div>
						</div>

						<div class="panel-body">

							<p class="text-semibold">Drag and Drop Files to Upload:</p>
							<div class="html5-uploader"><p>Your browser doesn't support native upload.</p></div>
						</div>
					</div>




								</form>
							</div>
						</div>
					</div>


   <!-- Close Form Modal -->
					<div id="modal_close_form" class="modal fade">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header bg-danger">
									<button type="button" class="close" data-dismiss="modal">&times;</button>
									<h5 class="modal-title">Project Close!</h5>
								</div>

								<form action="#">
									<div class="modal-body">

									<h6 class="text-semibold">Confirm details of Project before closing</h6>
									<p>After closure project will not accept anymore updates or changes. It will still continue to be tracked up until closer date. The project will still be present in any further analysis and in one or more dashboard chart.</p>

									<hr>
										<div class="form-group">

											<div class="row">
												<div class="col-sm-3">
													<span class="label label-primary label-block">Project Id:</span>
												</div>
												<div class="col-sm-9">
													<label name="pid"></label>
												</div>
												
											</div>

											<div class="row">
												<div class="col-sm-3">
													<span class="label label-primary label-block">Project Name: </span>
												</div>
												<div class="col-sm-9">
													<label name="pname"></label>
												</div>
											</div>

											<div class="row">
												<div class="col-sm-3">
													<span class="label label-primary label-block">Project Description: </span>
												</div>
												<div class="col-sm-9">
													<label name="pdesc"></label>
												</div>
											</div>

											<div class="row">
												<div class="col-sm-3">
													<span class="label label-primary label-block">Date Created: </span>
												</div>
												<div class="col-sm-9">
													<label name="pdate"></label>
												</div>
											</div>
											<hr>

											<div class="row">
												<div class="col-sm-3">
													<span class="label label-danger label-block">Schedule Closure: </span>
												</div>
												<div class="col-sm-9">
												<div class="input-group">
											    	<!--<input type="text" class="form-control daterange-single" value="03/18/2013">-->
											    	<input type="text" class="form-control pickadate" id="datepicker" value="June 29, 2016" placeholder="Try me&hellip;">
											    </div>
												</div>
											</div>											


										</div>
									</div>


									<div class="modal-footer">
										<button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
										<button type="submit" class="btn btn-primary">Close Project</button>
									</div>
								</form>
							</div>
						</div>
					</div>
					<!-- /vertical form modal -->


					{% endblock %}

     				<!--Parent core js override-->

    				{% block customjs%}
    				<script>


  			$('#modal_close_form').on('show.bs.modal', function (event) {
  						var button = $(event.relatedTarget) 
  						var pname = button.data('pname')
  						var pid = button.data('pid') 
  						var pdesc = button.data('pdesc')
  						var pdate = button.data('pdate') 
  						//console.log(pid);
  						var modal = $(this)
  						modal.find('label[name="pname"]').text(pname)
  						modal.find('label[name="pid"]').text(pid)
  						modal.find('label[name="pdesc"]').text(pdesc)
  						modal.find('label[name="pdate"]').text(pdate)
  						//Add date and project description
					})
   
    			</script>

    			<script>



    			$('#datepicker').pickadate({
                // Escape any “rule” characters with an exclamation mark (!). --Comment
  					format: 'mmmm d, yyyy',
  					selectMonths: true,
  					onStart: function ()
                	{
                		var date = new Date();
                		this.set('select', [date.getFullYear(), date.getMonth(), date.getDate()])
                	},
  				//formatSubmit: 'yyyy/mm/dd',--Comment
  				//hiddenPrefix: 'prefix__',--Comment
  				//hiddenSuffix: '__suffix'--Comment
  				//hiddenName: undefined,--Comment
				});
    			</script>


    			<!--

				Script to initiate ajax response will go here.

    			-->


    			{% endblock %}

     				<!--Parent chart js override-->



     				<!--Parent theme js override-->