ccaccounts/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.contrib.auth.views import(
    LoginView,
    LogoutView)

from ccaccounts.forms import AuthenticationForm as authform
from .views import (
    PasswordChangeView,
    PasswordChangeDoneView,
    HinyangoCreateUserView,
    HinyangoCreateUserDoneView,
    HinyangoResetUserView,
    HinyangoResetUserDoneView,
    DeleteUserStep1View,
    DeleteUserStep2View,
    ModifyUserDetailsView,
    HinyangoAccountRedirect)

# APP --> ACCOUNTS

urlpatterns = [
    #url(r'^login/$',LoginView.as_view(template_name='ccloginv3.html',authentication_form=authform),name='login'),
    url(r'^login/$',LoginView.as_view(template_name='hinyango_user_login.html',authentication_form=authform),name='login'),
    url(r'^logout/$',LogoutView.as_view(next_page=reverse_lazy('home')),name='logout'),
    url(r'^change/password/$',PasswordChangeView.as_view(),name='cpview'),
    url(r'^password/changed/$',PasswordChangeDoneView.as_view(),name='password_change_done'),
    url(r'^create/user/$',HinyangoCreateUserView.as_view(),name='add_hinyango_user'),
    url(r'^user/created/$',HinyangoCreateUserDoneView.as_view(),name='add_hinyango_user_done'),
    url(r'^reset/password/$',HinyangoResetUserView.as_view(),name='reset_password'),
    url(r'^password/reset/$',HinyangoResetUserDoneView.as_view(),name='reset_password_done'),
    url(r'^delete/user/$',DeleteUserStep1View.as_view(),name='delete_user'),
    url(r'^delete/user/(?P<uname>[a-zA-Z0-9]+)$',DeleteUserStep2View.as_view(),name='final_remove_user'),
    url(r'^modify/user/$',ModifyUserDetailsView.as_view(),name='modify_existing_user'),
    url(r'^login/redirect/$',HinyangoAccountRedirect.as_view(),name='login_redirect')
]

ccaccounts/models.py
"""
------------------------------------------------------------------------
Title: APP - Accounts - Models
Author: Matthew May
Date: 2016-01-04
Notes: User Account Profile Extends Django User
Notes:
------------------------------------------------------------------------
"""
from django.db import models
from django.contrib.auth.models import User

# APP - Accounts
class AccountProfile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.IntegerField(blank=False,null=True)
    department = models.CharField(max_length=100,blank=True,null=True)
    job_title = models.CharField(max_length=100,blank=True,null=True)
    tzone = models.CharField(max_length=100,blank=True,null=True)
    #first_name = models.CharField(max_length=50) This needs to be removed from the data base it is in the user model
    #last_name = models.CharField(max_length=50) This needs to be removed from the data base it is in the user model
    created_on = models.DateField(auto_now_add=True)
    def __str__(self):
        #return('first-name %s : last-name %s' % (self.user.first_name,self.user.last_name))
        if self.user.first_name == "":
            firstname = "First Name Not Set"
        else:
            firstname = self.user.first_name

        if self.user.last_name == "":
            lastname = "Last Name Not Set"
        else:
            lastname = self.user.last_name

        return("USER:"+self.user.username+"  FIRST NAME:"+firstname+"  LAST NAME:"+lastname+"  EMAIL:"+self.user.email)

# class ResidentTenant(models.Model):
#     tenant = models.CharField(max_length=100,blank=False,null=False,unique=True)
    

ccaccounts/templates/ccaccounts/add_new_user_done.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}New User Added{% endblock %} 
{% block custcss %}
<!--link rel="stylesheet" type="text/css" href="{% static '<<PATH TO ASSET>>' %}" />
<style> </style-->
{% endblock %} {% block main_content%}
<div class="panel panel-white">
    <div class="panel-heading">
        <h6 class="panel-title">User Add Successful</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li>
                    <a data-action="collapse" data-popup="tooltip" title="Collapse"></a>
                </li>
                <li>
                    <a data-action="reload" data-popup="tooltip" title="Reload"></a>
                </li>
                <li>
                    <a data-action="close" data-popup="tooltip" title="Close"></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
<p>New user was added successfully. Add another?</p>
            <div class="text-right row">
                <a class="btn btn-danger" name="cancelbtn" href="{% url 'viewproject' %}">Cancel</a>
                <a class="btn btn-primary" name="addanother" href="{% url 'add_hinyango_user' %}">Add User</a>
            </div>

    </div>
    {% endblock %}

ccaccounts/templates/ccaccounts/add_new_user_form.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}Add new user{% endblock %} 
{% block custcss %}
<!--link rel="stylesheet" type="text/css" href="{% static '<<PATH TO ASSET>>' %}" />
<style> </style-->
{% endblock %} {% block main_content%}
<div class="panel panel-white">
    <div class="panel-heading">
        <h6 class="panel-title">Add New User</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li>
                    <a data-action="collapse" data-popup="tooltip" title="Collapse"></a>
                </li>
                <li>
                    <a data-action="reload" data-popup="tooltip" title="Reload"></a>
                </li>
                <li>
                    <a data-action="close" data-popup="tooltip" title="Close"></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="row">
                    <div class="col-md-12">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="form-group">
                                    <span class="label border-left-danger label-striped">{{ error | escape }}</span>
                                    
                                </div>
                            {% endfor %}
                        <div class="form-group">
                            {{ field.label_tag}} {{ field }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="text-right row">
                <a class="btn btn-link" name="cancelbtn" href="{% url 'login_redirect' %}">Cancel</a>
                <button type="submit" class="btn bg-purple-400" name="newuser">Add User</button>
            </div>
        </form>
    </div>
    {% endblock %}

ccaccounts/templates/ccaccounts/ccloginv2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>Hinyango Login</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <!--external css-->
    <link href="{% static 'node_modules/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" type="text/css">

  </head>

  <body>

      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

	  <div id="login-page">
	  	<div class="container">
	  	
		      <form class="form-login" name="LoginForm" method="POST">
                  {% csrf_token %}
		        <h2 class="form-login-heading">Hinyango</h2>
		        <div class="login-wrap">
		            <input type="text" class="form-control" id="username" name="username" placeholder="User ID" autofocus>
		            <br>
		            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
		            <label class="checkbox">
		                <span class="pull-right">
		                    <!--a href="#"> Forgot Password?</a-->
		                </span>
		            </label>
		            <button class="btn btn-theme btn-block" type="submit"><i class="fa fa-lock"></i>LOGIN</button>
                    
		            <hr>

                    {% if messages %}
                            <div id="messages">
                                {% for message in messages %}
                                    <div class="login-social-link centered" style="color:red;">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            </div>
                    {% endif %}
                    
		        </div>
                
		      </form>	  	
	  	
	  	</div>
            <div class="background-image-fixed cover-image" style="background-image : url('{% static "assets/images/backgrounds/purple-background-images-8.jpg" %}')"></div>
	  </div>

    <!-- js placed at the end of the document so the pages load faster -->
    
    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/bootstrap3/dist/js/bootstrap.min.js' %}"></script>

    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="{% static 'js/jquery.backstretch.min.js' %}"></script>
    <script>
        $.backstretch("{% static 'assets/images/backgrounds/purple-background-images-8.jpg' %}", {speed: 0});
    </script>

  </body>
</html>

ccaccounts/templates/ccaccounts/ccloginv3.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>Hinyango Login</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <!--external css-->
    <link href="{% static 'node_modules/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" type="text/css">

  </head>

  <body>

      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

	  <div id="login-page">
	  	<div class="container">
	  	
		      <form class="form-login" name="LoginForm" method="POST">
                  {% csrf_token %}
		        <h2 class="form-login-heading">Hinyango</h2>
		        <div class="login-wrap">
		            <!--input type="text" class="form-control" id="username" name="username" placeholder="User ID" autofocus-->
                    {{ form.username.label_tag }}{{ form.username }}
		            <br>
		            <!--input type="password" class="form-control" id="password" name="password" placeholder="Password"-->
                    
                    {{ form.password.label_tag }}{{ form.password }}
		            <label class="checkbox">
		                <span class="pull-right">
		                    <a href="#"> Forgot Password?</a>
		                </span>
		            </label>
		            <button class="btn btn-theme btn-block" type="submit"><i class="fa fa-lock"></i>LOGIN</button>
                    
		            <hr>

                    {% if messages %}
                            <div id="messages">
                                {% for message in messages %}
                                    <div class="login-social-link centered" style="color:red;">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            </div>
                    {% endif %}
                    
		        </div>
                
		      </form>	  	
	  	
	  	</div>
            <div class="background-image-fixed cover-image" style="background-image : url('{% static "assets/images/backgrounds/purple-background-images-8.jpg" %}')"></div>
	  </div>

    <!-- js placed at the end of the document so the pages load faster -->
    
    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/bootstrap3/dist/js/bootstrap.min.js' %}"></script>

    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="{% static 'js/jquery.backstretch.min.js' %}"></script>
    <script>
        $.backstretch("{% static 'assets/images/backgrounds/purple-background-images-8.jpg' %}", {speed: 0});
    </script>

  </body>
</html>

ccaccounts/templates/ccaccounts/delete_user_step1.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}Add new user{% endblock %} {% block custcss %}
<!--link rel="stylesheet" type="text/css" href="{% static '<<PATH TO ASSET>>' %}" />
<style> </style-->
{% endblock %} {% block main_content%}
<div class="panel panel-white">
    <div class="panel-heading">
        <h6 class="panel-title">Remove User</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li>
                    <a data-action="collapse" data-popup="tooltip" title="Collapse"></a>
                </li>
                <li>
                    <a data-action="reload" data-popup="tooltip" title="Reload"></a>
                </li>
                <li>
                    <a data-action="close" data-popup="tooltip" title="Close"></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="row">
                    <div class="col-md-12">
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag}} {{ field }}
                            
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="text-right row">
                <a class="btn btn-link" name="cancelbtn" href="{% url 'viewproject' %}">Cancel</a>
                <button type="submit" class="btn bg-purple-400" name="deluser">Submit</button>
            </div>
        </form>
    </div>
    {% endblock %}

ccaccounts/templates/ccaccounts/delete_user_step2.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}Add new user{% endblock %} {% block custcss %}
<!--link rel="stylesheet" type="text/css" href="{% static '<<PATH TO ASSET>>' %}" />
<style> </style-->
{% endblock %} {% block main_content%}
<div class="panel panel-white">
    <div class="panel-heading">
        <h6 class="panel-title">Remove user - {{ remuser }}</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li>
                    <a data-action="collapse" data-popup="tooltip" title="Collapse"></a>
                </li>
                <li>
                    <a data-action="reload" data-popup="tooltip" title="Reload"></a>
                </li>
                <li>
                    <a data-action="close" data-popup="tooltip" title="Close"></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="row">
                    <div class="col-md-12">
                        {% if form.fields|length == 0 %}
                                                <div class="form-group">
                                                    The user has no assigned projects
                        </div>

                        {% endif %} 
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag}} {{ field }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="text-right row">
                <a class="btn btn-danger" name="cancelbtn" href="{% url 'viewproject' %}">Cancel</a>
                <button type="submit" class="btn btn-primary" name="newuser">Remove User</button>
            </div>
        </form>
    </div>
    {% endblock %}

ccaccounts/templates/ccaccounts/modify_user_details.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}Add new user{% endblock %} {% block custcss %}
<!--link rel="stylesheet" type="text/css" href="{% static '<<PATH TO ASSET>>' %}" />
<style> </style-->
{% endblock %} {% block main_content%}
<div class="panel panel-white">
    <div class="panel-heading">
        <h6 class="panel-title">Modify Existing User</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li>
                    <a data-action="collapse" data-popup="tooltip" title="Collapse"></a>
                </li>
                <li>
                    <a data-action="reload" data-popup="tooltip" title="Reload"></a>
                </li>
                <li>
                    <a data-action="close" data-popup="tooltip" title="Close"></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <form name="modform">
            <div class="row">
                <div class="form-group">
                    <label for="id_firstname">Username:</label>
                    <select name="username" class="form-control" placeholder="Username" id="id_username">
                        {% for data in userdata %} {% autoescape off %} {{ data.users }} {% endautoescape %} {% endfor %}
                        <!--option value="matthew">matthew</option>
                        <option value="george">george</option>
                        <option value="simon">simon</option>
                        <option value="michael">michael</option-->
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_lastname">Firstname:</label>
                    <input type="text" name="first_name" autofocus class="form-control" placeholder="First Name..." autocomplete="yes" maxlength="150" minlength="4" id="id_firstname" disabled="disabled" />
                </div>
                <div class="form-group">
                    <label for="id_lastname">Lastname:</label>
                    <input type="text" name="last_name" autofocus class="form-control" placeholder="Last Name..." autocomplete="yes" maxlength="150" minlength="4" id="id_lastname" disabled="disabled" />
                </div>
                <div class="form-group">
                    <label for="id_lastname">Email:</label>
                    <input type="text" name="email" autofocus class="form-control" placeholder="Email" autocomplete="yes" maxlength="150" minlength="4" required id="id_email" disabled="disabled" />
                </div>
                <div class="form-group">
                    <label for="id_department">Select Business Unit:</label>
                    <select name="department" class="form-control" placeholder="Business Unit" id="id_department" disabled="disabled">
                        {% for bu in business_unit %} {% autoescape off %} {{ bu.department }} {% endautoescape %} {% endfor %}
                    </select>
                </div>


                <div id='id_reactivate_div'></div>

            </div>
            <div class="text-right row">
                <a class="btn btn-link" name="cancelbtn" href="{% url 'viewproject' %}">Cancel</a>
                <button type="button" class="btn bg-purple-400 name="moduser" id="id_submitbutton" disabled="disabled">Modify Details</button>
            </div>
        </form>
    </div>
    {% endblock %} {% block chartcode%}

<script type="text/javascript" src="{% static 'assets/js/plugins/forms/styling/switch.min.js' %}"></script>
<script type="text/javascript">


var users_active = {
    {% for active in active_users %} 
    {% spaceless %}
    {{ active.username.strip }}: false,  
    {% endspaceless %}
    {% endfor %}
  // etc.
};
                // <div class="form-group">
                //     <div class="checkbox checkbox-switch" type=''>
                //         <label>
                //             <input type="checkbox" data-on-color="success" data-off-color="danger" data-on-text="Active" data-off-text="Inactive" class="switch" id="id_active_inactive">
                //         </label>
                //     </div>
                // </div>





$('#id_username').change(function() {
$("#id_firstname").prop("disabled", false);
$("#id_lastname").prop("disabled", false);
$("#id_email").prop("disabled", false);
$("#id_department").prop("disabled", false);
$("#id_submitbutton").prop("disabled", false);
contactpost($("#id_username").val(),'get_data')
});

$("#id_submitbutton").on("click", function() {

contactpost($("#id_username").val(),'action_post')
});


function contactpost(user,action){
var csrftoken = Cookies.get('csrftoken');


    if(action=='get_data'){

        var data_value = {'target': JSON.stringify('get_user_data'),
                          'user':JSON.stringify(user)} 
    }else{

        if($('#id_active_inactive').length == 0){
        var data_value = {'target': JSON.stringify('action_data'),
                          'user':   JSON.stringify(user),
                          'firstname': JSON.stringify($("#id_firstname").val()),
                          'lastname': JSON.stringify($("#id_lastname").val()),
                          'email': JSON.stringify($("#id_email").val()),
                          'department': JSON.stringify($("#id_department").val())} 
                  } else{
        var data_value = {'target': JSON.stringify('action_data'),
                          'user':   JSON.stringify(user),
                          'firstname': JSON.stringify($("#id_firstname").val()),
                          'lastname': JSON.stringify($("#id_lastname").val()),
                          'email': JSON.stringify($("#id_email").val()),
                          'department': JSON.stringify($("#id_department").val()),
                          'active_status':JSON.stringify($('#id_active_inactive').bootstrapSwitch('state')) } 

                          









                      }

    }

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

  $.ajax({
            type: "POST",
            url: "{% url 'modify_existing_user' %}",
            data: data_value,
    
            success: function(data) {
    
            if(data['result']=='success'){


            $("#id_firstname").val(data['firstname']);
            $("#id_lastname").val(data['lastname']);
            $("#id_email").val(data['email']);
            $("#id_department").val(data['department']);


            if(data['active']==false){

            html_add = `<div class="form-group">
                            <div class="checkbox checkbox-switch" type=''>
                                <label>
                                    <input type="checkbox" data-on-color="success" data-off-color="danger" data-on-text="Active" data-off-text="Inactive" class="switch" id="id_active_inactive">
                                </label>
                            </div>
                         </div>`;

            $('#id_reactivate_div').html(html_add);
            $(".switch").bootstrapSwitch();

            } else {

                $('#id_reactivate_div').html('');

            }

            


        }else if(data['result']=='complete'){

                                    new PNotify({
                                    title: 'Complete',
                                    text: data['message'],
                                    type: 'success',
                                    icon: 'glyphicon glyphicon-exclamation-sign',
                                    delay: 5000
                                    });

        }else{

                                    new PNotify({
                                    title: 'Error',
                                    text: data['message'],
                                    type: 'error',
                                    icon: 'glyphicon glyphicon-exclamation-sign',
                                    delay: 10000
                                    });

        }

                
            }
    
        });

}










</script>
{% endblock %}

ccaccounts/templates/ccaccounts/password_change_done.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}New User Added{% endblock %} {% block custcss %}
<!--link rel="stylesheet" type="text/css" href="{% static '<<PATH TO ASSET>>' %}" />
<style> </style-->
{% endblock %} {% block main_content%}
<div class="panel panel-white">
    <div class="panel-heading">
        <h6 class="panel-title">User Add Successful</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li>
                    <a data-action="collapse" data-popup="tooltip" title="Collapse"></a>
                </li>
                <li>
                    <a data-action="reload" data-popup="tooltip" title="Reload"></a>
                </li>
                <li>
                    <a data-action="close" data-popup="tooltip" title="Close"></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
<p>Your password was changed successfully.</p>
            <div class="text-right row">
                <a class="btn btn-primary" name="cancelbtn" href="{% url 'viewproject' %}">View Projects</a>
            </div>

    </div>
    {% endblock %}

ccaccounts/templates/ccaccounts/password_change_form.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}Change Password{% endblock %} {% block custcss %}
<!--link rel="stylesheet" type="text/css" href="{% static '<<PATH TO ASSET>>' %}" />
<style> </style-->
{% endblock %} {% block main_content%}
<div class="panel panel-white">
    <div class="panel-heading">
        <h6 class="panel-title">Change Password</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li>
                    <a data-action="collapse" data-popup="tooltip" title="Collapse"></a>
                </li>
                <li>
                    <a data-action="reload" data-popup="tooltip" title="Reload"></a>
                </li>
                <li>
                    <a data-action="close" data-popup="tooltip" title="Close"></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        
<form method="post">
    {% csrf_token %}
            <div class="row">
                <div class="row">
                    <div class="col-md-12">
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="form-group">
                                    <span class="label border-left-danger label-striped">{{ error | escape }}</span>
                                    
                                </div>
                            {% endfor %}
                        <div class="form-group">
                            {{ field.label_tag}} {{ field }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="text-right row">
                <a class="btn btn-link" name="cancelbtn" href="{% url 'viewproject' %}">Cancel</a>
                <button type="submit" class="btn bg-purple-400" name="newuser">Change Password</button>
            </div>


</form>
</div>


    </div>
    {% endblock %}

ccaccounts/templates/ccaccounts/reset_user_password_done.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}New User Added{% endblock %} {% block custcss %}
<!--link rel="stylesheet" type="text/css" href="{% static '<<PATH TO ASSET>>' %}" />
<style> </style-->
{% endblock %} {% block main_content%}
<div class="panel panel-white">
    <div class="panel-heading">
        <h6 class="panel-title">User Add Successful</h6>
        <div class="heading-elements">
            <ul class="icons-list">
                <li>
                    <a data-action="collapse" data-popup="tooltip" title="Collapse"></a>
                </li>
                <li>
                    <a data-action="reload" data-popup="tooltip" title="Reload"></a>
                </li>
                <li>
                    <a data-action="close" data-popup="tooltip" title="Close"></a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
<p>Password has been reset.</p>
            <div class="text-right row">
                <a class="btn btn-danger" name="cancelbtn" href="{% url 'viewproject' %}">Cancel</a>
                <a class="btn btn-primary" name="addanother" href="{% url 'reset_password' %}">Reset Another</a>
            </div>

    </div>
    {% endblock %}